services:
  brain:
    build:
      context: .
      dockerfile: Dockerfile.brain
    container_name: brain
    ports:
      - "8888:8888"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    depends_on:
      - brain
    restart: unless-stopped